- hosts: all
  gather_facts: False
  tasks:
  - name: "Incluindo usuarios e senhas do vcenter"
    include_vars: vcenter-vars.yml
  - name: "Criando vm"
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: teste-ansible
      template: template-ubuntu18.04
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "{{ inventory_hostname }}"
      hardware:
        memory_mb: 4096
        num_cpus: 6
        num_cpu_cores_per_socket: 3
        hotadd_cpu: True
        hotadd_memory: True
      networks:
      - name: vlan90
        ip: "{{ guest_custom_ip }}"
        netmask: 255.255.255.0
        gateway: 10.90.0.1
        type: static
        dns_servers: 
          - 200.11.0.2
          - 200.11.0.52
        dns_suffix:
          - ufrrj.br
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost