  - name: Baixando imagens para configurar o cluster
    shell: kubeadm config images pull

  - name: Iniciando Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address {{ad_addr}}

  - name: Gerando o token 
    command: kubeadm token create --print-join-command
    register: output
  
  - name: Copiando o token
    local_action: copy content={{ output.stdout }} dest={{ token_file }}

  - name: Copiando arquivos necessários
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Instalando network add-on weave
    shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"